# Generated by Django 5.0 on 2023-12-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('instructor', models.CharField(max_length=50)),
                ('duration', models.DateTimeField(verbose_name=1)),
            ],
        ),
    ]
