# Generated by Django 5.0 on 2024-01-11 08:44

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('instructor', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ImprovementArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('lectures', 'Lectures and videos'), ('material', 'Instructional materials i.e. readings'), ('assignments', 'Course assignments and projects'), ('exams', 'Graded assignments and exams'), ('forum', 'Forum'), ('additional-courses', 'Additional Courses')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('feedback_type', models.CharField(choices=[('complaint', 'Complaint'), ('suggestion', 'Suggestion')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('pdf', 'PDF')], default='text', max_length=4)),
                ('text_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf_contents/')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='course.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='course.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.coursecategory'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('employment_status', models.CharField(choices=[('student', 'Student'), ('job-full', 'Employed Full Time'), ('job-part', 'Employed Part Time'), ('self-employed', 'Self-employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('preferNo', 'Prefer not to say'), ('other', 'Other')], max_length=20)),
                ('experience_level', models.CharField(choices=[('junior', 'Junior (0-2 years experience)'), ('mid', 'Mid-level (2+ years experience)'), ('senior', 'Senior'), ('executive', 'Executive'), ('other', 'Other')], max_length=20)),
                ('course_rating', models.CharField(choices=[('excellent', 'Excellent'), ('very-good', 'Very good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('materials_rating', models.CharField(choices=[('extremely', 'Extremely useful'), ('very', 'Very useful'), ('somewhat', 'Somewhat useful'), ('not-so', 'Not so useful'), ('no', 'No useful at all')], max_length=20)),
                ('recommend_course', models.CharField(choices=[('definitely', 'Definitely'), ('maybe', 'Maybe'), ('not-sure', 'Not sure')], max_length=20)),
                ('comments', models.TextField()),
                ('improvement_areas', models.ManyToManyField(to='course.improvementarea')),
            ],
        ),
        migrations.CreateModel(
            name='MyCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
