# Generated by Django 5.0 on 2023-12-26 12:21

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_duration'),
    ]
