# Generated by Django 5.0 on 2023-12-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_mycourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycourses',
            name='category',
        ),
    ]
